# Generated by Django 2.2 on 2018-12-21 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
