# Generated by Django 2.2 on 2018-12-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0007_myblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
