# Generated by Django 2.2 on 2018-12-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0009_remove_myblog_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myblog',
            name='status',
        ),
        migrations.AlterField(
            model_name='myblog',
            name='create_time',
            field=models.TextField(null=True),
        ),
    ]
