# Generated by Django 2.2 on 2019-01-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0010_auto_20181224_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
